config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'statics#index'
  get 'skills', to: 'statics#skills'
  get 'web_applications', to: 'statics#web_applications'
  get 'resume', to: 'statics#resume'
  get 'contact', to: 'statics#contact'
  get 'modal', to: 'statics#modal'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/projects.rb
module Projects
  extend ActiveSupport::Concern

  Myora = {
    "self": 'myora',
    "tools": [
      'Ruby 3.0.1',
      'Rails 6.1.3',
      'Stimulus.js',
      'Parcel.js',
      'Tailwind CSS',
      'PostgreSQL',
      'GitHub',
      'Heroku'
    ],
    "images": [
      'myora_1.gif',
      'myora_2.gif'
    ],
    "description": 'A Ruby on Rails application for casual or professional free time-keeping.  Organize your project timesheets, collaborate with a team, watch your expected earnings grow with every entry in real time.'
  }.freeze

  Foodtalk = {
    "self": 'FoodTalk',
    "tools": [
      'Ruby 2.6.2',
      'Rails 5.1.7',
      'jQuery',
      'Bootstrap CSS',
      'Auth0',
      'PostgreSQL',
      'WordPress API',
      'RSpec',
      'Capybara/Selenium',
      'GitLab',
      'Nginx',
      'Capistrano',
    ],
    "images": [
      'foodtalk_1.gif',
      'foodtalk_2.gif',
      'foodtalk_3.gif'
    ],
    "description": "An online education platform dedicated to eLearning for SNAP eligible Georgia residents.  Home for health and fitness articles and nutritious recipes from University of Georgia's College of Family and Consumer Sciences.  Full administrative console for user statistics, reporting, CSV exports, and data management."
  }.freeze

  GenerationFitness = {
    "self": 'Generation Fitness',
    "tools": [
      'Ruby 2.5.3',
      'Rails 5.2.3',
      'Bootstrap CSS',
      'Adobe Creative Suite',
      'SendGrid',
      'PostgreSQL',
      'GitHub',
      'Heroku'
    ],
    "images": [
      'gfit_1.gif',
      'gfit_2.gif'
    ],
    "description": 'The website for my commercial fitness center startup, Generation Fitness, Fort Myers.  Full integration with club management software for online enrollment.'
  }.freeze

  AdamGoodman = {
    "self": 'This Portfolio',
    "tools": [
      'Ruby 3.0.1',
      'Rails 6.1.3',
      'Tailwind CSS',
      'WebPacker',
      'StimulusJS',
      'Adobe Creative Suite',
      'GitHub',
      'Heroku'
    ],
    "images": [
      'ag_1.gif',
      'ag_2.gif',
      'ag_3.gif'
    ],
    "description": 'You are here!'
  }.freeze

  CONTACT = [
    {
      "value": 'adam@adam-goodman.com',
      "email": 'adam@adam-goodman.com',
      "icon": 'fas fa-envelope'
    },
    {
      "value": '860.818.1440',
      "icon": 'fas fa-mobile-alt'
    },
    {
      "value": 'linkedin.com/in/adamjgoodman',
      "link": 'https://linkedin.com/in/adamjgoodman',
      "icon": 'fab fa-linkedin'
    },
    {
      "value": 'github.com/adamjgoodman',
      "link": 'https://github.com/adamjgoodman',
      "icon": 'fab fa-github'
    }
  ].freeze
end

app/controllers/statics_controller.rb
# frozen_string_literal: true

class StaticsController < ApplicationController
  include StaticsHelper
  include Projects

  def index; end

  def skills
    render partial: '/skills/show', status: :ok
  end

  def web_applications
    render partial: '/web_applications/show', status: :ok
  end

  def resume
    render partial: '/resume/show', status: :ok
  end

  def contact
    render partial: '/contact/show', status: :ok
  end

  def modal
    @image = params[:image]
    render partial: '/modal/modal', status: :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statics_helper.rb
# frozen_string_literal: true

module StaticsHelper

  SKILLS = [
    {
      'title': 'Ruby',
      'icon': 'https://cdn.icon-icons.com/icons2/2107/PNG/512/file_type_ruby_icon_130186.png'
    },
    {
      'title': 'Rails',
      'icon': 'icons/rails.png'
    },
    {
      'title': 'HTML5',
      'icon': 'https://cdn.icon-icons.com/icons2/1488/PNG/512/5352-html5_102567.png'
    },
    {
      'title': 'JavaScript',
      'icon': 'https://cdn.icon-icons.com/icons2/2415/PNG/512/javascript_original_logo_icon_146455.png'
    },
    {
      'title': 'jQuery',
      'icon': 'https://cdn3.iconfinder.com/data/icons/popular-services-brands/512/jquery-512.png'
    },
    {
      'title': 'Stimulus',
      'icon': 'icons/stimulus.png'
    },
    {
      'title': 'CSS3',
      'icon': 'https://cdn.icon-icons.com/icons2/1488/PNG/512/5351-css3_102605.png'
    },
    {
      'title': 'Tailwind',
      'icon': 'icons/tailwind.png'
    },
    {
      'title': 'Bootstrap',
      'icon': 'https://cdn.icon-icons.com/icons2/2415/PNG/512/bootstrap_plain_logo_icon_146619.png'
    },
    {
      'title': 'PostgreSQL',
      'icon': 'https://cdn.icon-icons.com/icons2/2415/PNG/512/postgresql_plain_logo_icon_146389.png'
    },
    {
      'title': 'RSpec',
      'icon': 'https://rspec.info/images/logo.png',
    },
    {
      'title': 'Selenium',
      'icon': 'https://www.selenium.dev/images/selenium_logo_square_green.png'
    },
    {
      'title': 'Capybara',
      'icon': 'icons/capybara.png'
    },
    {
      'title': 'Git Control',
      'icon': 'https://cdn.icon-icons.com/icons2/2107/PNG/512/file_type_git_icon_130581.png'
    },
    {
      'title': 'Photoshop',
      'icon': 'https://cdn.icon-icons.com/icons2/2107/PNG/512/file_type_photoshop_icon_130268.png'
    }
  ].freeze
end

app/views/contact/_show.html.erb
<div class="fade-in-left min-h-screen h-full mt-8">
  <% Projects::CONTACT.each do |contact| %>
    <div class="rounded-md bg-white shadow-sm border p-2 my-3 w-full lg:w-3/4 mx-auto">
      <div class="grid grid-cols-4">
        <div class="col-span-1 text-blue-500 bg-gray-50 py-6 rounded">
          <i class="fa-2x <%= contact[:icon] %>"></i>
        </div>
        <div class="col-span-3 text-gray-500 text-sm md:text-lg flex items-center justify-center font-bold">
          <% if contact[:link] %>
            <%= link_to contact[:value], contact[:link] %>
          <% elsif contact[:email] %>
            <%= mail_to contact[:value], contact[:email] %>
          <% else %>
            <%= contact[:value] %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adam Goodman</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/modal/_modal.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<div data-action="click->application#closeModal" data-application-target="closeModal" class="fixed fade-in z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true">
  <div class="flex items-center justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">

    <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true"></div>

    <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

    <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-4xl sm:w-full">
      <%= image_tag @image, class: "w-full" %>
    </div>
  </div>
</div>

app/views/resume/_education.html.erb
<div class="w-full bg-white border rounded shadow-sm grid grid-cols-6 mt-4">
  <div class="flex justify-center bg-gray-50 rounded p-3 col-span-2 lg:col-span-1">
    <%= image_tag "icons/ucf.png", class: "img-fluid max-h-20 mt-1" %>
  </div>
  <div class="col-span-4 text-gray-500 text-left p-3">
    <span class="text-md lg:text-xl font-bold">Full Stack Web Development</span>
    <div class="text-xs lg:text-sm mb-1">
      University of Central Florida
    </div>
    <hr />
    <details class="m-3 text-xs">
      <summary>Expand</summary>
      <div class="fade-in mx-3">
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Ruby / Rails
        </div>
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          HTML/CSS
        </div>
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Data structures & Algorithms
        </div>
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Git Control
        </div>
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Independent and collaborative web development projects
        </div>
      </div>
    </details>
  </div>
</div>

<div class="w-full bg-white border rounded shadow-sm grid grid-cols-6 mt-4">
  <div class="flex justify-center bg-gray-50 rounded p-3 col-span-2 lg:col-span-1">
    <%= image_tag "icons/fsu.png", class: "img-fluid max-h-20 mt-1" %>
  </div>
  <div class="col-span-3 lg:col-span-4 text-gray-500 text-left p-3">
    <span class="text-md lg:text-xl font-bold">B.S. - Applied Economics</span>
    <div class="text-xs lg:text-sm mb-1">
      Florida State University
    </div>
    <hr />
    <details class="m-3 text-xs">
      <summary>Expand</summary>
      <div class="fade-in mx-3">
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Econometrics/Economic Data Analysis
        </div>
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Business Calculus
        </div>
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Accounting/Finance
        </div>
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Marketing
        </div>
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Entrepreneurship
        </div>
      </div>
    </details>
  </div>
</div>

app/views/resume/_show.html.erb
<div class="fade-in-left min-h-screen h-full mt-8 mb-4">
  <%= render partial: "resume/work" %>
  <hr class="my-5 w-50 mx-auto" />
  <%= render partial: "resume/education" %>
</div>

app/views/resume/_work.html.erb
<div class="w-full bg-white border rounded shadow-sm grid grid-cols-6">
  <div class="flex justify-center bg-gray-50 rounded p-3 col-span-2 lg:col-span-1">
    <%= image_tag "icons/uga.png", class: "img-fluid max-h-20 mt-1" %>
  </div>
  <div class="col-span-4 text-gray-500 text-left p-3">
    <span class="text-md lg:text-xl font-bold">Web Developer Principal</span>
    <div class="text-xs lg:text-sm mb-1">
      University of Georgia SNAP Education
    </div>
    <hr />
    <details class="m-3 text-xs">
      <summary>Expand</summary>
      <div class="fade-in mx-3">
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Improved, maintained, and scaled FoodTalk.org using Ruby 2.6.3, Rails 5.1.7, Bootstrap, jQuery and more
        </div>
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Introduced red-green-refactor test-driven development with RSpec, Capybara, and Selenium
        </div>
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Utilized GitLab version control working both as a small, collaborative team and independently
        </div>
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Developed an administrative interface to visualize user data and manage partner organizations
        </div>
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Created an in-house ticketing system to manage and address debugging, requests, and suggestions
        </div>
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Refactored application architecture to support growing partner organizations and expansion outside Georgia
        </div>
      </div>
    </details>
  </div>
</div>

<div class="w-full bg-white border rounded shadow-sm grid grid-cols-6 mt-4">
  <div class="flex justify-center bg-gray-50 rounded p-3 col-span-2 lg:col-span-1">
    <%= image_tag "icons/gfit.png", class: "img-fluid max-h-20 mt-1" %>
  </div>
  <div class="col-span-4 text-gray-500 text-left p-3">
    <span class="text-md lg:text-xl font-bold">Vice President/Owner-Operator</span>
    <div class="text-xs lg:text-sm mb-1">
      Generation Fitness Clubs
    </div>
    <hr />
    <details class="m-3 text-xs">
      <summary>Expand</summary>
      <div class="fade-in mx-3">
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Increased monthly club revenue from $15,000 to $26,000
        </div>
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Increased monthly membership dues by $5,700
        </div>
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Designed and launched www.mygenerationfitness.com
        </div>
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Configured and troubleshot club management software for digital contracts, Point of Sale, sales reporting, and payroll
        </div>
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Led team of personal trainers and member service staff
        </div>
      </div>
    </details>
  </div>
</div>

<div class="w-full bg-white border rounded shadow-sm grid grid-cols-6 mt-4">
  <div class="flex justify-center bg-gray-50 rounded p-3 col-span-2 lg:col-span-1">
    <%= image_tag "icons/cxp.png", class: "img-fluid max-h-20 mt-1" %>
  </div>
  <div class="col-span-4 text-gray-500 text-left p-3">
    <span class="text-md lg:text-xl font-bold">Club Manager</span>
    <div class="text-xs lg:text-sm mb-1">
      Cardio Express Fitness Centers
    </div>
    <hr />
    <details class="m-3 text-xs">
      <summary>Expand</summary>
      <div class="fade-in mx-3">
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Manage staff of 8-12 trainers, front desk, and cleaning staff
        </div>
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Produce 40-50% of monthly membership sales
        </div>
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Consistently meet or exceed sales KPI's
        </div>
        <div class="my-2 bg-gray-50 rounded w-100 px-3 py-2 border shadow-sm">
          Promoted from Assistant Manager to General Manager after 3 months of service
        </div>
      </div>
    </details>
  </div>
</div>

app/views/skills/_show.html.erb
<div class="fade-in-left grid grid-cols-3 md:grid-cols-5 w-full mx-auto justify-center my-8">
  <% StaticsHelper::SKILLS.each do |skill| %>
    <div class="font-bold text-sm p-5 items-center flex flex-col">
      <div class="bg-white bg-opacity-75 rounded-full p-4 shadow-md hover:shadow-none">
        <%= image_tag skill[:icon], width: 50, height: 50, referrerpolicy: "no-referrer" %>
      </div>
      <div class="my-5">
        <%= skill[:title] %>
      </div>
    </div>
  <% end %>
</div>

app/views/statics/_nav.html.erb
<nav class="w-full text-white text-center text-sm font-bold cursor-pointer xs:border-0 lg:border lg:shadow-md rounded-md">
  <%= link_to skills_path, data: { action: "ajax:success->application#navigate", remote: true } do %>
    <div class="p-5 rounded lg:hover:bg-white hover:bg-opacity-50 hover:text-green-400">
      Skills & Tools
    </div>
  <% end %>
  <%= link_to web_applications_path, data: { action: "ajax:success->application#navigate", remote: true } do %>
    <div class="p-5 lg:hover:bg-white hover:bg-opacity-50 hover:text-green-400">
      Web Applications
    </div>
  <% end %>
  <%= link_to resume_path, data: { action: "ajax:success->application#navigate", remote: true } do %>
    <div class="p-5 lg:hover:bg-white hover:bg-opacity-50 hover:text-green-400">
      Resume
    </div>
  <% end %>
  <%= link_to contact_path, data: { action: "ajax:success->application#navigate", remote: true } do %>
    <div class="p-5 rounded lg:hover:bg-white hover:bg-opacity-50 hover:text-green-400">
      Contact
    </div>
  <% end %>
</nav>

app/views/statics/index.html.erb
<div data-controller="application" class="bg-gradient-to-r from-green-400 to-blue-500 h-full flex flex-col w-full text-white">
  <div class="h-full">
    <div class="px-4 pt-8">
      <div class="grid grid-cols-12">
        <div class="block md:hidden col-span-12 grid grid-cols-3 border-b mb-3">
          <div class="px-4 flex items-end col-span-2">
            <%= image_tag "me.png", class: "pt-3 shadow-b max-w-full h-auto align-middle" %>
          </div>
          <div>
            <%= render partial: "nav" %>
          </div>
        </div>
        <div class="hidden md:block col-span-3 xl:col-span-2">
          <div class="flex flex-wrap justify-center">
            <div class="px-4">
              <%= image_tag "me.png", class: "me pt-3 shadow-b max-w-full h-auto align-middle" %>
            </div>
            <%= render partial: "nav" %>
          </div>
        </div>
        <div class="relative w-full text-center col-span-12 md:col-span-9 xl:col-span-10">
          <div class="font-bold text-5xl lg:text-8xl mb-3">
            Adam Goodman
          </div>
          <div class="text-xl lg:text-4xl font-thin justify-center flex px-16">
            Full Stack Ruby on Rails Developer
          </div>
          <div class="w-full lg:w-4/5 mx-auto" data-application-target="navigation modal">
            <%= render partial: "skills/show" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/web_applications/_show.html.erb
<div class="fade-in-left h-full mt-8">
  <div class="grid container mx-auto p-2 text-xs">
    <div class="w-full md:w-11/12 mx-auto rounded shadow-sm bg-white border">
      <h1 class="text-2xl text-center font-bold text-gray-500 mt-2">
        <%= Projects::Myora[:self] %> <i class="far fa-clock text-green-500"></i>
      </h1>
      <hr class="my-2" />
      <div class="grid grid-flow-row grid-cols-2 md:grid-cols-4 gap-2 w-11/12 mx-auto">
        <% Projects::Myora[:tools].each do |tool| %>
          <div class="bg-blue-400 rounded"><%= tool %></div>
        <% end %>
      </div>
      <div class="w-full md:w-11/12 mx-auto text-sm text-gray-500 my-3">
        <%= Projects::Myora[:description] %>
      </div>
      <div data-controller="slideshow" data-slideshow-index-value="0" class="w-11/12 md:w-4/5 mx-auto tex-sm text-blue-400 my-3">
        <div class="grid grid-cols-10 border rounded">
          <div class="h-full flex items-center justify-center bg-gray-50 rounded shadow-sm">
            <button data-action="slideshow#previous"><i class="fas fa-arrow-alt-circle-left fa-2x"></i></button>
          </div>
          <div class="col-span-8">
            <% Projects::Myora[:images].each_with_index do |image, index| %>
              <div class="fade-in-left bg-gray-50" data-slideshow-target="slide" id="<%= index + 1 == Projects::Myora[:images].count %>">
                <%= link_to modal_path(image: image), data: { action: "ajax:success->application#modal", remote: true } do %>
                  <%= image_tag image, class: "img-fluid slideshow" %>
                <% end %>
              </div>
            <% end %>
          </div>
          <div class="h-full flex items-center justify-center bg-gray-50 rounded">
            <button data-action="slideshow#next"><i class="fas fa-arrow-alt-circle-right fa-2x"></i></button>
          </div>
        </div>
        <div class="mt-4 d-flex justify-center">

        </div>
      </div>
    </div>
    <br />
    <div class="w-full md:w-11/12 mx-auto rounded shadow-sm bg-white border">
      <h1 class="text-2xl text-center font-bold text-gray-500 mt-2">
        <%= link_to "https://foodtalk.org", target: "_blank" do %>
          <%= Projects::Foodtalk[:self] %>
          <i class="fas fa-utensils text-yellow-500 ml-1"></i>
        <% end %>
      </h1>
      <hr class="my-2" />
      <div class="grid grid-flow-row grid-cols-2 lg:grid-cols-4 xl:grid-cols-6 gap-2 w-11/12 mx-auto">
        <% Projects::Foodtalk[:tools].each do |tool| %>
          <div class="bg-blue-400 rounded"><%= tool %></div>
        <% end %>
      </div>
      <div class="w-full md:w-11/12 mx-auto text-sm text-gray-500 my-3">
        <%= Projects::Foodtalk[:description] %>
      </div>
      <div data-controller="slideshow" data-slideshow-index-value="0" class="w-11/12 md:w-4/5 mx-auto tex-sm text-blue-400 my-3">
        <div class="grid grid-cols-10 border rounded">
          <div class="h-full flex items-center justify-center bg-gray-50 rounded shadow-sm">
            <button data-action="slideshow#previous"><i class="fas fa-arrow-alt-circle-left fa-2x"></i></button>
          </div>
          <div class="col-span-8">
            <% Projects::Foodtalk[:images].each_with_index do |image, index| %>
              <div class="fade-in-left bg-gray-50" data-slideshow-target="slide" id="<%= index + 1 == Projects::Foodtalk[:images].count %>">
                <%= link_to modal_path(image: image), data: { action: "ajax:success->application#modal", remote: true } do %>
                  <%= image_tag image, class: "img-fluid slideshow" %>
                <% end %>
              </div>
            <% end %>
          </div>
          <div class="h-full flex items-center justify-center bg-gray-50 rounded">
            <button data-action="slideshow#next"><i class="fas fa-arrow-alt-circle-right fa-2x"></i></button>
          </div>
        </div>
        <div class="mt-4 d-flex justify-center">

        </div>
      </div>
    </div>
    <br />
    <div class="w-full md:w-11/12 mx-auto rounded shadow-sm bg-white border">
      <%= link_to "http://www.mygenerationfitness.com", target: "_blank" do %>
        <h1 class="text-2xl text-center font-bold text-gray-500 mt-2">
          <%= Projects::GenerationFitness[:self] %>
          <i class="fas fa-dumbbell text-red-500 ml-1"></i>
        </h1>
      <% end %>
      <hr class="my-2" />
      <div class="grid grid-flow-row grid-cols-2 md:grid-cols-4 gap-2 w-11/12 mx-auto flex justify-center">
        <% Projects::GenerationFitness[:tools].each do |tool| %>
          <div class="bg-blue-400 rounded"><%= tool %></div>
        <% end %>
      </div>
      <div class="w-full md:w-11/12 mx-auto text-sm text-gray-500 my-3">
        <%= Projects::GenerationFitness[:description] %>
      </div>
      <div data-controller="slideshow" data-slideshow-index-value="0" class="w-11/12 md:w-4/5 mx-auto tex-sm text-blue-400 my-3">
        <div class="grid grid-cols-10 border rounded">
          <div class="h-full flex items-center justify-center bg-gray-50 rounded shadow-sm">
            <button data-action="slideshow#previous"><i class="fas fa-arrow-alt-circle-left fa-2x"></i></button>
          </div>
          <div class="col-span-8">
            <% Projects::GenerationFitness[:images].each_with_index do |image, index| %>
              <div class="fade-in-left bg-gray-50" data-slideshow-target="slide" id="<%= index + 1 == Projects::GenerationFitness[:images].count %>">
                <%= link_to modal_path(image: image), data: { action: "ajax:success->application#modal", remote: true } do %>
                  <%= image_tag image, class: "img-fluid slideshow" %>
                <% end %>
              </div>
            <% end %>
          </div>
          <div class="h-full flex items-center justify-center bg-gray-50 rounded">
            <button data-action="slideshow#next"><i class="fas fa-arrow-alt-circle-right fa-2x"></i></button>
          </div>
        </div>
        <div class="mt-4 d-flex justify-center">

        </div>
      </div>
    </div>

    <br />

    <div class="w-full md:w-11/12 mx-auto rounded shadow-sm bg-white border">
      <%= link_to "http://www.mygenerationfitness.com", target: "_blank" do %>
        <h1 class="text-2xl text-center font-bold text-gray-500 mt-2">
          <%= Projects::AdamGoodman[:self] %>
          <i class="fas fa-smile text-green-500 ml-1"></i>
        </h1>
      <% end %>
      <hr class="my-2" />
      <div class="grid grid-flow-row grid-cols-2 md:grid-cols-4 gap-2 w-11/12 mx-auto flex justify-center">
        <% Projects::AdamGoodman[:tools].each do |tool| %>
          <div class="bg-blue-400 rounded"><%= tool %></div>
        <% end %>
      </div>
      <div class="w-11/12 mx-auto text-sm text-gray-500 my-3">
        <%= Projects::AdamGoodman[:description] %>
      </div>
      <div data-controller="slideshow" data-slideshow-index-value="0" class="w-11/12 md:w-4/5 mx-auto tex-sm text-blue-400 my-3">
        <div class="grid grid-cols-10 border rounded">
          <div class="h-full flex items-center justify-center bg-gray-50 rounded shadow-sm">
            <button data-action="slideshow#previous"><i class="fas fa-arrow-alt-circle-left fa-2x"></i></button>
          </div>
          <div class="col-span-8">
            <% Projects::AdamGoodman[:images].each_with_index do |image, index| %>
              <div class="fade-in-left bg-gray-50" data-slideshow-target="slide" id="<%= index + 1 == Projects::AdamGoodman[:images].count %>">
                <%= link_to modal_path(image: image), data: { action: "ajax:success->application#modal", remote: true } do %>
                  <%= image_tag image, class: "img-fluid slideshow" %>
                <% end %>
              </div>
            <% end %>
          </div>
          <div class="h-full flex items-center justify-center bg-gray-50 rounded">
            <button data-action="slideshow#next"><i class="fas fa-arrow-alt-circle-right fa-2x"></i></button>
          </div>
        </div>
        <div class="mt-4 d-flex justify-center">

        </div>
      </div>
    </div>
  </div>
</div>